/* Generated By:JavaCC: Do not edit this line. LovelaceConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LovelaceConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int APAR = 7;
  /** RegularExpression Id. */
  int FPAR = 8;
  /** RegularExpression Id. */
  int BEGIN = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int PV = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int BOOL = 13;
  /** RegularExpression Id. */
  int VOID = 14;
  /** RegularExpression Id. */
  int ATRIB = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int PRINT = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int VIRGULA = 22;
  /** RegularExpression Id. */
  int DEF = 23;
  /** RegularExpression Id. */
  int READ = 24;
  /** RegularExpression Id. */
  int IGUAL = 25;
  /** RegularExpression Id. */
  int MAIS = 26;
  /** RegularExpression Id. */
  int MENOS = 27;
  /** RegularExpression Id. */
  int ASTER = 28;
  /** RegularExpression Id. */
  int BARRA = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int MAIOR = 32;
  /** RegularExpression Id. */
  int MENOR = 33;
  /** RegularExpression Id. */
  int ID = 34;
  /** RegularExpression Id. */
  int NUMLITERAL = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"let\"",
    "\"(\"",
    "\")\"",
    "\"begin\"",
    "\"end\"",
    "\";\"",
    "\"Float\"",
    "\"Bool\"",
    "\"Void\"",
    "\":=\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"print\"",
    "\"true\"",
    "\"false\"",
    "\",\"",
    "\"def\"",
    "\"read\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\">\"",
    "\"<\"",
    "<ID>",
    "<NUMLITERAL>",
  };

}
